FROM rocker/r-ver:4.4.2

# System dependencies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        gcc \
        g++ \
        git \
        libomp-dev && \
    rm -rf /var/lib/apt/lists/*

# R package dependencies
RUN R -e "install.packages(c('remotes', 'rpart', 'rpart.plot', 'MASS'), repos = 'https://cloud.r-project.org')"
RUN R -e "remotes::install_github('StochasticTree/stochtree', ref = 'r-0.4.5')"

# Set working directory
WORKDIR /workspace

# Launch R process
CMD ["R"]