name: Reproducing JSS Examples via Github Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker-examples-r:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t stochtree-r -f Dockerfile-R . 

      - name: Clear plots from the figures/ directory
        run: |
          rm ${{ github.workspace }}/figures/R/*.pdf

      - name: Run demo script(s)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace stochtree-r Rscript scripts/R/custom-interface-bart-linreg.R

      - name: Store output plots as run artifact
        uses: actions/upload-artifact@v4
        with:
          name: jss-r-plots
          path: |
            figures/R/
